### ISSUE TITLE
Error Handling on Public Pages 

### ISSUE THREAD

**Issue by ethanszeto** [Northeastern-Science-Magazine/nusci-website#105]
### Task Necessity
- In the public pages controller we still use the deprecated version of error handling, which caused some outdated routes.
### Task Description
- Your task is to redefine the public pages controller such that it follows the standard error handling convention for the site. For error handling examples, look at other controllers.

**Comment by Amrani-Farouk-Hossam-Eddine** [comment]
Hi, i'm interesting in this issue and i want to work on it if there is no one currenlty workeing on it
