### ISSUE TITLE
Writing the Articles View

### ISSUE THREAD

**Issue by ethanszeto** [Northeastern-Science-Magazine/nusci-website#12]
# Research/Learning
- Every request that we make to the database returns a JSON of data. However, we don’t - want our data to be returned to the user as a JSON. 
- This task requires looking at existing JSON parsers so that we can transform it into something more viewable.
# Actionable Task 
- Your task is to develop a view file that takes in a Json, and transform it into an HTML view. This HTML page should be barebones for now, only writing in article title, author, image, body text and sources. Add appropriate CSS styles (aka main.css only). 
- If CSS is necessary, utilize our agreed upon frontend library. 
- If necessary, you can create a new JSON parser.

**Comment by kevinlu4588** [comment]
JSON ayyyy

**Comment by ethanszeto** [comment]
lol
